name: Tests

on:
  pull_request_target:
    branches:
      - "main"
  push:
    branches:
      - "main"

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.13.*"
          - "1.14.*"

    permissions:
      contents: read
      id-token: write

    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            9236a389bd48b984df91adc1bc924620.r2.cloudflarestorage.com:443
            api.github.com:443
            cgr.dev:443
            checkpoint-api.hashicorp.com:443
            dl.google.com:443
            fulcio.sigstore.dev:443
            github.com:443
            go.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            releases.hashicorp.com:443
            storage.googleapis.com:443
            sum.golang.org:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: "contains(github.event_name, 'pull_request')"
        with:
          ref: refs/pull/${{ env.PR_NUMBER }}/merge
          persist-credentials: false

      - name: checkout from push event
        if: github.event_name == 'push'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ./go.mod
          cache: false
          check-latest: true

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - run: go mod download

      - run: go build -v .

      - run: TF_ACC=1 go test -v -cover ./internal/provider/

  check:
    permissions:
      actions: read
    needs:
      - test
    runs-on: ubuntu-latest
    if: always() # always run as required and if any dependent job is skipped, this is skipped if not always
    steps:
      - uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            9236a389bd48b984df91adc1bc924620.r2.cloudflarestorage.com:443
            api.github.com:443
            cgr.dev:443
            checkpoint-api.hashicorp.com:443
            dl.google.com:443
            fulcio.sigstore.dev:443
            github.com:443
            go.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            releases.hashicorp.com:443
            storage.googleapis.com:443
            sum.golang.org:443
            tuf-repo-cdn.sigstore.dev:443

      - uses: step-security/workflow-conclusion-action@e624ac1e0582b6498a4ddaa8cf623532fc7b95ea # v3.0.9

      - name: Handle conclusion
        env:
          CONCLUSION: ${{ env.WORKFLOW_CONCLUSION }}
        working-directory: /tmp
        run: |
          if [[ "${CONCLUSION}" == "success" ]]; then
            echo "${CONCLUSION}" && exit 0
          elif [[ "${CONCLUSION}" == "failure" ]]; then
            echo "${CONCLUSION}" && exit 1
          fi
